# Generated by Django 5.1.1 on 2024-09-23 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_restaurant_yelp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='favorited_by',
            field=models.ManyToManyField(default=False, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
