# Generated by Django 5.1.1 on 2024-09-24 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_restaurant_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
