# Generated by Django 5.1.1 on 2024-09-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='favorited',
        ),
    ]
