# Generated by Django 5.1.1 on 2024-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_restaurant_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
