# Generated by Django 5.1.1 on 2024-09-23 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_restaurant_favorited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
