# Generated by Django 5.1.1 on 2024-09-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
