# Generated by Django 5.1.1 on 2024-09-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_restaurant_image_url'),
        ('main_app', '0009_alter_review_restaurant'),
    ]

    operations = [
    ]
