# Generated by Django 5.1.1 on 2024-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_restaurant_yelp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
