# Generated by Django 5.1.1 on 2024-09-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_restaurant_yelp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='yelp_id',
        ),
    ]
